[project]
name = "dsr-python-intro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.4.3",
    "jupyter>=1.1.1",
    "pandas>=2.3.3",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
]
